### PR TITLE
Rename toile-server; add run method for notion-server

### PR DESCRIPTION
**Pull request by SamWilsn**
Mostly just fixing the same of the server executable.

### CODE REVIEW

**Review by gjtrowbridge — APPROVED** [review]
Seems like there's a decent chance some of this may change depending on the direction we go with the web server stuff, but this diff seems to just be renaming already-landed stuff, so looks good to me.

**Comment by SamWilsn** [comment]
bird r+

**Comment by SamWilsn** [comment]
@gjtrowbridge Could you expand on which parts might need to change depending on the choice of web framework?

My goal here was to abstract passing configuration (`NotionBuilder`), so that the server can be started from the CLI (which lives in `src/bin/notion-server.rs`) or from future tests.

**Comment by gjtrowbridge** [comment]
@SamWilsn I guess what I was trying to say was that this feels like a lot of boilerplate to add this early in the process.  It feels a bit premature to add all this abstraction before we have any web server code written, but it's possible I'm missing the point and I'll feel differently as we move along in the project.  Either way, I appreciate you putting this together!

**Pull request merged**
